mongo_uri = "mongodb+srv://prashanth01071995:pradsml%402025@cluster0.fsbic.mongodb.net/?retryWrites=true&w=majority"
AUTH0_CLIENT_ID = "kCzbOqlzvHacYpQJDYiWnP7OKOhclI3y"
AUTH0_CLIENT_SECRET = "DqgdBrUTmTwrs7naVjp4NlgaGXiQxfN7wignYyMtuf8gYTKkl5P_A9e2JNr-4J7k"
AUTH0_DOMAIN = "dev-etexxrcmop374jwn.us.auth0.com"
APP_SECRET_KEY = "ALongRandomlyGeneratedString"
AUTH0_AUDIENCE = "https://dev-etexxrcmop374jwn.us.auth0.com/api/v2/"